# Generated by Django 5.1 on 2024-08-18 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stoker', '0002_advisers_image_alter_clients_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='advisers',
            name='seen',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='clients',
            name='seen',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='comments',
            name='seen',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='features',
            name='seen',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='services',
            name='seen',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
